name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]  # 매일 자정 실행
  workflow_dispatch:              # 수동 실행 가능
  push: {branches: ["master", "main"]}  # master/main 브랜치에 푸시 시 실행

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          config_display: ""  # 불필요한 플러그인 비활성화
          filename: github-metrics.svg
